### PR TITLE
Add ID in toc tree to easily create correct links when using raw toc

### PR DESCRIPTION
**Pull request by marmotz**

### CODE REVIEW

**Comment by marmotz** [comment]
Thanks !!!

**Comment by Amaury** [comment]
Wow, you are on fire. We can't stop you!  :-)

**Comment by marmotz** [comment]
Look what i've done with:
- your SkrivMarkup ;
- my source file: https://github.com/atoum/atoum-documentation/blob/skriv/fr/Contents/chapter1.skriv
- my generator: https://github.com/marmotz/sia/blob/master/bin/sia

http://hynea.mattlab.com/atoum-documentation/fr/Output/chapter1.html

Later, I want to create a real generic tool to make documentation (from SkrivMarkup !!!), but for now, i just want to generate a quick doc for atoum :)

**Comment by Amaury** [comment]
I _love_ that!  :-D

**Pull request merged**
