### PR TITLE
fix missing backslash to Exception :)

### PR DESCRIPTION
**Pull request by marmotz**

### CODE REVIEW

**Comment by Amaury** [comment]
I was about to commit the same code fix when I saw your PR...  ;-)

**Comment by marmotz** [comment]
Sorry
Le 4 janv. 2013 11:43, "Amaury Bouchard" notifications@github.com a
écrit :

**Comment by Amaury** [comment]
No pb. In fact, this line doesn't exist anymore.
=> You can get your TOC, in HTML (`<ul>`-based list) or raw (PHP array).

Enjoy!  :-)

**Comment by marmotz** [comment]
Oops... a non clickable toc :p

**Comment by Amaury** [comment]
Ahahaha!
You're right. I was eager to push the functionality, I forgot the links...  :-)

I'll do it this afternoon.

**Comment by Amaury** [comment]
OK, your pull request has been merged. Thank you!

**Pull request merged**
